CREATE TABLE USERS(
USERNAME VARCHAR(30) NOT NULL,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
MIDDLENAMES VARCHAR(50),
PASSWORD VARCHAR(100),
TOWN VARCHAR(30),
GENDER VARCHAR(10),
EMAIL VARCHAR(50),
POSTCODE VARCHAR(10),
UNI VARCHAR(50),
BOOKSOWNED INT(10),
CONSTRAINT USERS_SELF_KEY1 FOREIGN KEY(BOOKSOWNED) REFERENCES BOOK(ISBN),
CONSTRAINT USERS_PRIMARY_KEY PRIMARY KEY(USERNAME));

CREATE TABLE BOOK(
ISBN INT(10) NOT NULL AUTO_INCREMENT,
BOOKNAME VARCHAR(100),
AUTHOR VARCHAR(30),
BLURB VARCHAR(100),
PUBLISHER VARCHAR(30),
PRICE NUMBER,
GENRE VARCHAR(15),
PUBLISHDATE DATE,
OFFERTYPE VARCHAR(10),
CONSTRAINT BOOK_SELF_KEY1 FOREIGN KEY(GENRE) REFERENCES GENRE(GENRENAME),
CONSTRAINT BOOK_PRIMARY_KEY PRIMARY KEY(BOOKID));


CREATE TABLE GENRE(
GENRENAME VARCHAR(15),
CONSTRAINT GENRE_PRIMARY_KEY PRIMARY KEY(GENRENAME));

CREATE TABLE AUTHOR(
AUTHORID INT(10) NOT NULL AUTO_INCREMENT,
AUTHORNAME VARCHAR (30),
BOOKS INT(10),
BIO VARCHAR(100),
CONSTRAINT AUTHOR_SELF_KEY1 FOREIGN KEY (BOOKS) REFERENCES BOOK(BOOKID),
CONSTRAINT AUTHOR_PRIMARY_KEY PRIMARY KEY(AUTHORID));

CREATE TABLE PUBLISHER (
PUBLISHERID INT(10),
NAME VARCHAR(15),
PUBLISHED INT(10),
CONSTRAINT PUBLISHER_PRIMARY_KEY PRIMARY KEY (PUBLISHERID));

CREATE TABLE UNI(
UNINAME VARCHAR(25),
TOWN VARCHAR(25),
CONSTRAINT UNI_SELF KEY1 FOREIGN KEY (TOWN) REFERENCES TOWN(TOWNNAME); 
CONSTRAINT UNI_PRIMARY_KEY PRIMARY KEY(UNINAME));

CREATE TABLE TOWN(
TOWNNAME  VARCHAR(20),
COUNTRY VARCHAR(20),
CONSTRAINT TOWN_PRIMARY_KEY PRIMARY KEY (TOWNNAME,COUNTRY));