CREATE TABLE BOOK (
TITLE				CHAR(40) NOT NULL,
ISBN				INT(13) NOT NULL,
AUTHOR				CHAR(40),
GENRE				CHAR(20),
PAGELENGTH			NUMERIC(4),
PAPERORHARDBACK		CHAR(12),
RELEASEYEAR			NUMERIC(4),
CONSTRAINT BOOK_SELF_KEY FOREIGN KEY (TITLE) REFERENCES BOOK (ISBN),
CONSTRAINT BOOK_PRIMARY_KEY PRIMARY KEY (ISBN));

CREATE TABLE USERPROFILE (
NAME				CHAR(40) NOT NULL,
EMAIL				CHAR(40) NOT NULL,
CITY				CHAR(40),
CONTACT				NUMERIC(13),
CONSTRAINT USER_PRIMARY_KEY PRIMARY KEY (EMAIL));

CREATE TABLE OFFERTYPE (
FREE				CHAR(1),
TRADE				CHAR(1),
SELL				CHAR(1));

CREATE TABLE GENRE (
BOOKGENRE			CHAR(15));

CREATE TABLE PUBLISHER (
PUBLISHERNAME		CHAR(40));

CREATE TABLE TOWN (
TOWNNAME			CHAR(20));

CREATE TABLE AUTHOR (
AUTHORNAME			CHAR(30));
